### ISSUE TITLE
Will the new Hash syntax be supported?

### ISSUE THREAD

**Issue by dolzenko** [awesome-print/awesome_print#126]
Subject. Sorry if already discussed. I think it could be optional too (probably only trigger if all keys in a hash are `Symbol`s)

**Comment by waldyr** [comment]
After almost two years it is implemented now on https://github.com/awesome-print/awesome_print/commit/239c990a1325f403f93112ff872e31c21f6c8784

**Comment by NullVoxPopuli** [comment]
I was looking for how to print the non hash-rocket hashes, and.... am I doing it right?

```
> ap({a: :b}, { new_hash_syntax: true}) 
{
    :a => :b
}
```

that's printing the old way, where I'd expect it to print
```
{
  a: :b
}
```

Using:
```
$ irb
irb(main):001:0> require 'awesome_print'
=> true
irb(main):002:0> AwesomePrint.version
=> "1.8.0"
```

**Comment by waldyr** [comment]
@NullVoxPopuli  try
```
ap({a: :b}, ruby19_syntax: true)
```

**Comment by tanduong** [comment]
This is not working!

```
> ap({a: 1}, ruby19_syntax: true)
{
  :a => 1
}
```

**Comment by tanduong** [comment]
Oh, it works with version 1.8!
