### ISSUE TITLE
Should make "==" usage safer

### ISSUE THREAD

**Issue by kikonen-fiksu** [awesome-print/awesome_print#154]
With various occasions "==" checks inside awesome_print trigger internal errors in calling program.

Most often problem seems to be hit around here.

``` ruby
lib/awesome_print/formatter.rb:66
```

I.e. script tries to check if object is ENV, but various objects actually are not implementing "==" method safely, thus they trigger internal errors via awesome_inspect.

Worse is that fixing those problematic gems are not my own, but part of rails (and other gems); so can't actually fix them.

It would be better that "ap" would either do some catching of errors, or due this check safer way.

For example,
I recently hit issue with this on this case:

```
undefined method `to_sym' for #<Object:0x007fc3a086ffe0>.
/actionpack-3.2.13/lib/action_dispatch/http/mime_type.rb:239:in `block in =='
/actionpack-3.2.13/lib/action_dispatch/http/mime_type.rb:238:in `each'
/actionpack-3.2.13/lib/action_dispatch/http/mime_type.rb:238:in `any?'
/actionpack-3.2.13/lib/action_dispatch/http/mime_type.rb:238:in `=='
/awesome_print-1.2.0/lib/awesome_print/formatter.rb:66:in `awesome_self'
/awesome_print-1.2.0/lib/awesome_print/formatter.rb:28:in `format'
...

```

**Comment by mttrs** [comment]
Thanks a lot!

**Comment by jmoody** [comment]
Hurray!
