### ISSUE TITLE
NoMethodError: undefined method `to_i' - Devise Model

### ISSUE THREAD

**Issue by CodyStringham** [awesome-print/awesome_print#165]
Throwing this error in rails c when I try to look up a devise model. Is there a way around this? 

``` ruby
User.all # works as intended
User.last # NoMethodError: undefined method `to_i'
```

**Comment by miamiruby** [comment]
awesome print does not support the inet field type of postgres

**Comment by maurogeorge** [comment]
@miamiruby could you please update to the last release? This was fixed on the 1.6.0.

**Comment by tonyrosario** [comment]
Can confirm that updating to 1.6.1 fixes the issue.  Thanks!

**Comment by miamiruby** [comment]
no longer an issue for me
