### ISSUE TITLE
request official 1.6.2 release

### ISSUE THREAD

**Issue by pstare** [awesome-print/awesome_print#204]
Can we get an official release for 1.6.2? Branch 'master' currently fixes issue #202, but our internal policy is not to use bundler with git gems.

**Comment by srinath-v** [comment]
:+1:

**Comment by fdr** [comment]
Ditto, I'm also hitting the bug in sequel in #202

**Comment by waldyr** [comment]
I'm marking this and #202 as resolved. Tested with 1.7.0 and it now works properly.

![screen shot 2016-06-19 at 1 15 11 pm](https://cloud.githubusercontent.com/assets/1893997/16178493/f1c06e42-361f-11e6-93b4-bca2fa6d93a9.png)

**Comment by gerrywastaken** [comment]
As always, if anybody is still running into this issue on the latest build then please let us know by tagging us in a comment.
