### ISSUE TITLE
ActiveRecord::Result break AwesomePrint formatter.

### ISSUE THREAD

**Issue by louim** [awesome-print/awesome_print#215]
Hello! 

When an [`ActiveRecord::Result`](http://api.rubyonrails.org/classes/ActiveRecord/Result.html) is returned, AwesomePrint break. For example:
```
ap ActiveRecord::Base.connection.exec_query('SELECT id, title, body FROM posts')
```
will result in:
```
NoMethodError: undefined method `keys' for #<Array:0x007ffb0b7dee30>
	from /Users/louim/.gem/ruby/2.2.3/gems/awesome_print-1.6.1/lib/awesome_print/formatter.rb:103:in `awesome_hash'
	from /Users/louim/.gem/ruby/2.2.3/gems/awesome_print-1.6.1/lib/awesome_print/formatter.rb:67:in `awesome_self'
	from /Users/louim/.gem/ruby/2.2.3/gems/awesome_print-1.6.1/lib/awesome_print/formatter.rb:28:in `format'
	from /Users/louim/.gem/ruby/2.2.3/gems/awesome_print-1.6.1/lib/awesome_print/inspector.rb:137:in `unnested'
	from /Users/louim/.gem/ruby/2.2.3/gems/awesome_print-1.6.1/lib/awesome_print/inspector.rb:104:in `awesome'
	from /Users/louim/.gem/ruby/2.2.3/gems/awesome_print-1.6.1/lib/awesome_print/core_ext/kernel.rb:10:in `ai'
	from /Users/louim/.gem/ruby/2.2.3/gems/awesome_print-1.6.1/lib/awesome_print/core_ext/kernel.rb:20:in `ap'
	from /Users/louim/.gem/ruby/2.2.3/gems/awesome_print-1.6.1/lib/awesome_print/inspector.rb:31:in `output_value'
	from /Users/louim/.gem/ruby/2.2.3/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
	from /Users/louim/.gem/ruby/2.2.3/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
	from /Users/louim/.gem/ruby/2.2.3/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/louim/.gem/ruby/2.2.3/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/louim/.gem/ruby/2.2.3/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/louim/.gem/ruby/2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/louim/.gem/ruby/2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/louim/.gem/ruby/2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
... 2 levels...
	from /Users/louim/.gem/ruby/2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /Users/louim/.gem/ruby/2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/louim/.gem/ruby/2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/louim/.gem/ruby/2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /Users/louim/.gem/ruby/2.2.3/gems/spring-1.4.4/lib/spring/commands/rails.rb:6:in `call'
	from /Users/louim/.gem/ruby/2.2.3/gems/spring-1.4.4/lib/spring/command_wrapper.rb:38:in `call'
	from /Users/louim/.gem/ruby/2.2.3/gems/spring-1.4.4/lib/spring/application.rb:183:in `block in serve'
	from /Users/louim/.gem/ruby/2.2.3/gems/spring-1.4.4/lib/spring/application.rb:156:in `fork'
	from /Users/louim/.gem/ruby/2.2.3/gems/spring-1.4.4/lib/spring/application.rb:156:in `serve'
	from /Users/louim/.gem/ruby/2.2.3/gems/spring-1.4.4/lib/spring/application.rb:131:in `block in run'
	from /Users/louim/.gem/ruby/2.2.3/gems/spring-1.4.4/lib/spring/application.rb:125:in `loop'
	from /Users/louim/.gem/ruby/2.2.3/gems/spring-1.4.4/lib/spring/application.rb:125:in `run'
	from /Users/louim/.gem/ruby/2.2.3/gems/spring-1.4.4/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/louim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/louim/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

**Comment by Kache** [comment]
I just came across this as well. Workaround is to not let the console inspect it:

    > result = ActiveRecord::Base.connection.select_all("select * from users limit 1;"); nil
    nil
    > puts result.inspect # manually inspect it

**Comment by Kache** [comment]
Traced this to `ActiveRecord::Result#to_hash`, which returns an array of hashes.

Suggestions:

 * Check `object.respond_to?(:to_ary)` first, and handle `Array.try_convert(object)` as an array.

 * `AwesomePrint::Formatter#awesome_self` can call `Hash.try_convert(object)` (which calls `#to_hash` rather than calling `object.to_hash` directly. This way, a more meaningful `TypeError` is returned:

    > Hash.try_convert(ActiveRecord::Base.connection.select_all("select * from users limit 1;"))
    TypeError: can't convert ActiveRecord::Result to Hash (ActiveRecord::Result#to_hash gives Array)

Aside from that, I've submitted a post to [the Rails core mailing list](https://groups.google.com/forum/?fromgroups#!forum/rubyonrails-core) about the issue (post to be approved) with the following:

>==ActiveRecord::Result#to_hash doesn't return a hash==

>[ActiveRecord::Result#to_hash](https://github.com/rails/rails/commit/59f7780a3454a14054d1d33d9b6e31192ab2e58b#diff-56dacac8e4a23c4e1d4f63562fa5d6d1R23)

>It's unexpected for `#to_hash` to _not_ return a hash, e.g. [AwesomePrint](https://github.com/michaeldv/awesome_print) checks and uses `#to_hash` to inspect hash-convertible objects, as noted in [an AwesomePrint issue](https://github.com/michaeldv/awesome_print/issues/215).
>
>Ruby core even expects `Hash` from `#to_hash`:
>
    > Hash.try_convert(ActiveRecord::Base.connection.select_all("select * from users limit 1;"))
    TypeError: can't convert ActiveRecord::Result to Hash (ActiveRecord::Result#to_hash gives Array)
>
>`#to_ary` already exists, meaning users of `ActiveRecord::Result#to_hash` should really be using `ActiveRecord::Result#to_a`

**Comment by louim** [comment]
@Kache Thanks for following up, hadn't had the time to dig in myself. :+1:

**Comment by dreyks** [comment]
It is actually already fixed in master by 4ee2ade5f72677e2afd92033e6f0d4c244a8e43d

**Comment by Kache** [comment]
Nice!

**Comment by waldyr** [comment]
@gerrywastaken I think this is resolved. Wdyt?

**Comment by gerrywastaken** [comment]
Just tested it on the AP v1.7.0 release using Rails 5 RC1 and it is working for me.

@waldyr feel free to close.

@louim or anybody else, if this is still not working then please tag myself and @waldyr in any comments you post here.

**Comment by waldyr** [comment]
I'm going to mark this as resolved. If anybody else find it not working a version upgrade will fix it.
