### ISSUE TITLE
require 'rake' in gemspec

### ISSUE THREAD

**Issue by dreyks** [awesome-print/awesome_print#218]
Why is there a
```ruby
require "rake"
```
in `awesome_print.gemspec`? It breaks `bundle install` on first run i.e. when there are no gems installed in system

**Comment by rcrogers** [comment]
I'm also getting a crash from this.

**Comment by gerrywastaken** [comment]
This has been fixed thanks to #216 and #222, however I'm still waiting on some sort of access to push up to Rubygems. see: https://github.com/michaeldv/awesome_print/issues/234

**Comment by dreyks** [comment]
any updates on the situation?

**Comment by gerrywastaken** [comment]
@dreyks I'd love to push this fix, but as mentioned, I do not have push access to Rubygems. @michaeldv made a promising post a few days ago: https://github.com/michaeldv/awesome_print/issues/238

Things are really out of my hands regarding this and I don't wish to be too pushy as I'm sure Michael is very busy and will get to this as soon as he can.

**Comment by gerrywastaken** [comment]
@dreyks, @rcrogers and anybody else reading. Version 1.7.0 has just been pushed up to Rubygems with this fix. I'm very sorry that it took so long and thank you for your persistence.
