### ISSUE TITLE
Release fix for integration with Mail < v2.6.4

### ISSUE THREAD

**Issue by gerrywastaken** [awesome-print/awesome_print#234]
There seems to be a great deal of people running into the issue fixed by #200, so I would like to release the fix as soon as possible. However I do not currently have push access on Rubygems.

See the following PRs for more details:
https://github.com/michaeldv/awesome_print/pull/200
https://github.com/michaeldv/awesome_print/pull/206

**Comment by gerrywastaken** [comment]
Also see: https://github.com/michaeldv/awesome_print/issues/199#issuecomment-218565362

**Comment by gerrywastaken** [comment]
> @michaeldv wrote
> @IslamAzab Added you to https://github.com/michaeldv/awesome_print/settings/collaboration as well, please coordinate new version release with the folks there.

@IslamAzab Are you able to see the collaboration page? We have a few fixes in master which have been reported by many people in many different projects and I'm currently unable to push the fixes to rubygems so I'm wondering if you have been given access?

**Comment by IslamAzab** [comment]
@gerrywastaken I don't think so.

**Comment by gerrywastaken** [comment]
@IslamAzab Thanks for leting me know anyway. :)

**Comment by gerrywastaken** [comment]
I've now pushed this to Rubygems with version 1.7.0. 👍
