### ISSUE TITLE
Release next version to Rubygems

### ISSUE THREAD

**Issue by gerrywastaken** [awesome-print/awesome_print#239]
Just a checklist so that I don't forget anything

- [x] make sure change log is up to date with all user impacting changes
- [x] determine if this should be a patch or minor release
- [x] bump version file
- [x] tag release
- [x] get a sanity check from @waldyr 
- [x] push to rubygems
- [x] notify all related issues / PRs and close were appropriate

**Comment by gerrywastaken** [comment]
I think #226 and #200 warrant a minor bump. Also there were quite a few changes made before I came on board which are not linked to any pull request in the change log, so this reinforces the need. I'm guessing they were not major or they would have ended up on the 2.0.0 branch.

**Comment by gerrywastaken** [comment]
@waldyr are you able to sanity check everything for me when you get a chance?

I updated the version files, changelog and tagged the last commit.

**Comment by waldyr** [comment]
Everything listed was addressed. Nice work @gerrywastaken 👍

**Comment by gerrywastaken** [comment]
Released 1.7.0 to Rubygems so I'm closing this.

If you commenting to alert of an issue caused by this release, please tag me in your comment to make sure I get notified.
