### ISSUE TITLE
Stack Error Too Deep in Rails 5.0.0.1

### ISSUE THREAD

**Issue by SylarRuby** [awesome-print/awesome_print#269]
Was this meant to be used with Rails? In my `Gemfile`, in the development block, I have 

```
gem 'awesome_print', :require => 'ap'
```
Now in the rails console:

```
BigDecimal.new("2.11") #=> stack error too deep

```

**Comment by gerrywastaken** [comment]
I haven't been able to replicate the issue you mentioned.

```
> bundle exec rails c
Loading development environment (Rails 4.2.5.2)
irb: warn: can't alias context from irb_context.
irb(main):001:0> BigDecimal.new("2.11")
=> #<BigDecimal:7f9fc85fa658,'0.211E1',18(18)>
irb(main):003:0> AwesomePrint::version
=> "1.7.0"
irb(main):004:0> exit
> grep awesome_print Gemfile
  gem 'awesome_print', :require => 'ap'
```

Btw, you should need to specify `:require => 'ap'`

**Comment by SylarRuby** [comment]
Hey @gerrywastaken! Sorry. Digging further, the culprit was caused by another gem. Thanks for your response!

**Comment by gerrywastaken** [comment]
@SylarRuby no worries at all and cheers for the update :)
