### ISSUE TITLE
Does this gem work propertly on rails5 ? 

### ISSUE THREAD

**Issue by piotr-galas** [awesome-print/awesome_print#274]
Hello, after migrate rails to version 5.0.0.1, awesome-print stop working. 
`require "awesome_print"` return false.

I'm not sure if i need  additional config to use this gem propertly with rails 5 ?
Does anyone have similar problem?

**Comment by gerrywastaken** [comment]
Should work, but I haven't specifically tested with 5.0.0.1. At work now but will check it out asap.

**Comment by miccheng** [comment]
+1 to this not working on Rails 5.0.0.1. I have a fresh install.

**Comment by swilson223** [comment]
This is what I'm getting as an error using Rails 5.0.0.1 

`2.3.1 :001 > require "awesome_print"
LoadError: cannot load such file -- awesome_print
	from /Users/shawnwilson/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/shawnwilson/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/shawnwilson/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/shawnwilson/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from (irb):1
	from /Users/shawnwilson/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/console.rb:65:in `start'
	from /Users/shawnwilson/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/shawnwilson/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/shawnwilson/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/shawnwilson/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/shawnwilson/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/shawnwilson/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/shawnwilson/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/shawnwilson/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
	from /Users/shawnwilson/Desktop/PatrolVault-SaaS/PatrolVault/bin/rails:9:in `<top (required)>'
	from /Users/shawnwilson/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/shawnwilson/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/shawnwilson/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/shawnwilson/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
	from /Users/shawnwilson/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/shawnwilson/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'`

**Comment by gerrywastaken** [comment]
@piotr-galas @miccheng @swilson223 

Sorry for taking so long to get back to all of you. I just tried this and did not run into any error.

* Are you still running into this error?
* Are you sure that awesome_print is in your Gemfile, in the correct environment and that you ran bundle install after adding it?
* Are you all using RVM or just @swilson223. I'm using chruby on the machine where I'm testing.

If anybody knows what the issue is I'll accept a pull request, but at the moment I'm unable to reproduce it so I can't really do anything other than ask questions.

**Comment by swilson223** [comment]
no worries I am using RVMm, i will try to reinstall it and let you know if / what the issue was if i am successful

**Comment by swilson223** [comment]
Ok so i just did a reinstall, everything is working although:
```2.3.1 :001 > require "awesome_print"
 => false```

aside from that 

gem 'awesome_print', require: "ap" 

bundle install works.. 

It did not however work by just running $ gem install awesome_print.. which i could see an issue with new folks trying to use it as your not telling them in the docs that it must be explicitly added to gem file. 

just my two sense! Thanks Great gem btw!

**Comment by gerrywastaken** [comment]
@swilson223 

> Ok so i just did a reinstall
Great to hear. :)

> everything is working although:
> 2.3.1 :001 > require "awesome_print" => false

If require is returning false, I believe it means that awesome print has already been loaded.
https://ruby-doc.org/core-2.3.1/Kernel.html#method-i-require

Even if you didn't require it in your own code, it could have been required by another gem (e.g. pry requires awesome_print if it's available).

> It did not however work by just running $ gem install awesome_print
That's very strange as it works here:

```
~ gem uninstall awesome_print
~ gem install awesome_print
Fetching: awesome_print-1.7.0.gem (100%)
Successfully installed awesome_print-1.7.0
```

Did you get an error? However the code that handles gem installing is not part of the awesome_print project. It might be an issue with your rubygems install. If you are not getting any errors but awesome_print is not being installed, you could try running:

`gem install --verbose awesome_print`

If you see that it is being installed, but you cannot require it after install (keeping in mind that require returning false means it has already been required) then it might be an issue with RVM configuration not looking in the right location for system gems.

I hope it's just a misunderstanding of require returning false, I initially found that confusing myself at one point.

Thanks heaps for getting back to me with an update.

**Comment by MacgyverMartins** [comment]
I am having the same error
I install with `gem install awesome_print`

When a run `rails c` and `require "awesome_print"`
I got the error
`LoadError: cannot load such file -- awesome_print`

**Comment by rodrigobdz** [comment]
@MacgyverMartins Installing it via Bundler as stated in https://github.com/awesome-print/awesome_print/issues/274#issuecomment-258655886 works.

**Comment by dinesh16** [comment]
try `spring stop` then run `rails c`
