### ISSUE TITLE
awesome_print requires rails?

### ISSUE THREAD

**Issue by TechRsch** [awesome-print/awesome_print#298]
AP runs fine in my Rails app but fails quickly in my Sinatra app.  Does it require Rails?  If so, should that not be in the documentation and gemspec?  Thanks.

I should mention that the failure appears to be on the method convert_to_hash and, if diagnostics are to be believed, it is in formatter.rb:122.  Debugging Ruby in Sinatra while using EventMachine and FayeWebsocket is quite an experience, however.  So, YMMV.

**Comment by thbar** [comment]
A quick note to tell you that I'm using awesome_print just fine in a lot of plain ruby projects, without problems.

**Comment by gerrywastaken** [comment]
@TechRsch It shouldn't require rails at all. Perhaps you could share the error... otherwise I'm not sure how I can help.
