### ISSUE TITLE
Warning: constant ::Fixnum is deprecated (ruby 2.4.0)

### ISSUE THREAD

**Issue by thbar** [awesome-print/awesome_print#299]
I'm upgrading an app to ruby 2.4.0 and noticed this warning, so I thought I'd report it here (although it's not blocking at this point) :

```
/Users/thbar/.rvm/gems/ruby-2.4.0/gems/awesome_print-1.7.0/lib/awesome_print/formatters/base_formatter.rb:31: warning: constant ::Fixnum is deprecated
```

Related:

* http://blog.bigbinary.com/2016/11/18/ruby-2-4-unifies-fixnum-and-bignum-into-integer.html
* https://www.ruby-lang.org/en/news/2016/12/25/ruby-2-4-0-released/

**Comment by gerrywastaken** [comment]
@thbar Thanks for that :)

**Comment by gerrywastaken** [comment]
Merged that change, there are still some references to fixnum which should probably be updated though. Will update here when I've pushed a new release to Rubygems.

**Comment by alexandre-mbm** [comment]
Workaround: http://stackoverflow.com/a/42336144/3391915
```sh
export RUBYOPT="-W0"
```

**Comment by codebycliff** [comment]
How long before a release is going to be cut? I'm also experiencing this deprecation warning on 2.4.0. I'm trying to figure out if I should just point to master in my gemfile or wait for a release. Thanks in advance for your time.

**Comment by Dr4hcir** [comment]
Same question here. Before getting into the workaround, is there a fix coming soon? Thanks for the help

**Comment by tisba** [comment]
Looks like this is fixed in master, maybe we can cut a new version soonish? :)

**Comment by evaryont** [comment]
It's be nice to cut a release soon, though I don't know if you want to tackle any of the [issues in the v2 milestone](https://github.com/awesome-print/awesome_print/issues?q=is%3Aopen+is%3Aissue+milestone%3Av2), or perhaps instead a 1.8 release?

**Comment by mattscilipoti** [comment]
Since this update has been ready for a while, I recommend a 1.x release.

**Comment by Zhomart** [comment]
It will be nice to have `1.8.0` or `1.7.1` sooner.

**Comment by alexandre-mbm** [comment]
> Since this update has been ready for a while, I recommend a 1.x release.

Here I have **1.7.0** and it is buggy also. The command `gem install` does not update.

**Comment by kikonen** [comment]
Q: what's status on this?

**Comment by imajes** [comment]
so sorry -- life has been one project after another. Well, a year between releases can't be bad for a simple stable gem ;) 

Here's to [1.8.0](https://rubygems.org/gems/awesome_print/versions/1.8.0) ! :beers: 👍 💯

**Comment by thbar** [comment]
@imajes don't apologise, you owe use nothing :-) Thanks for the release!

**Comment by artmai** [comment]
I had the same error and I've just added the following in my gem file and it worked:
gem 'selenium-webdriver'
gem 'chromedriver-helper'

Hope that helps!
