### ISSUE TITLE
Left align hash keys?

### ISSUE THREAD

**Issue by jfelchner** [awesome-print/awesome_print#308]
One of the things that has constantly bugged me about `awesome_print` (but it's still awesome!) is the fact that the hash keys are right aligned.  It makes it extremely difficult to get a sense of nesting.

I like that the `=>` are aligned, but I'd love a way to left-align the keys.

Possible?

**Comment by Pysis868** [comment]
This may help you, and any one else that finds this issue:
[Issue #83 - Some hashes are incorrect printed](https://github.com/awesome-print/awesome_print/issues/83)

> michaeldv commented on [Sep 19, 2013](https://github.com/awesome-print/awesome_print/issues/83#issuecomment-24780400)
> That's default behavior. If you would like hash keys to be left-aligned use :indent => -n (negative value).
