### ISSUE TITLE
warning: method redefined; discarding old - complaint in the verbose mode

### ISSUE THREAD

**Issue by matkoniecz** [awesome-print/awesome_print#310]
to replicate - create file with `require 'awesome_print'`, name it awesome_bug.rb

run `ruby -v awesome_bug.rb`

what happens:

```
ruby 2.3.4p301 (2017-03-30 revision 58214) [i386-linux-gnu]
/home/mateusz/.gem/ruby/2.3.0/gems/awesome_print-1.7.0/lib/awesome_print/core_ext/array.rb:19: warning: method redefined; discarding old -
/home/mateusz/.gem/ruby/2.3.0/gems/awesome_print-1.7.0/lib/awesome_print/core_ext/array.rb:19: warning: method redefined; discarding old &
```

expected: lack of warnings

**Comment by matkoniecz** [comment]
Is it maybe a rspec bug?

**Comment by matkoniecz** [comment]
It turns out to be fixed in master.

**Comment by imajes** [comment]
so sorry -- life has been one project after another. Well, a year between releases can't be bad for a simple stable gem ;) 

Here's to [1.8.0](https://rubygems.org/gems/awesome_print/versions/1.8.0) ! :beers: 👍 💯
