### ISSUE TITLE
please, release a new version

### ISSUE THREAD

**Issue by matkoniecz** [awesome-print/awesome_print#312]
after checking current master it turns out that #310 is fixed but unreleased

Can you consider releasing a new version?

**Comment by mattscilipoti** [comment]
There are many votes for a new release in #299 too.  

As far as I know, your supportive community can not assist with releases.  We can only wait patiently (with a nudge, now and then).  

What is causing the delay?  Is it something we can help with?

**Comment by imajes** [comment]
so sorry -- life has been one project after another. Well, a year between releases can't be bad for a simple stable gem ;) 

Here's to [1.8.0](https://rubygems.org/gems/awesome_print/versions/1.8.0) ! :beers: 👍 💯
