### ISSUE TITLE
NameError: undefined local variable or method `dotfile' for #<AwesomePrint::Inspector

### ISSUE THREAD

**Issue by dawncold** [awesome-print/awesome_print#316]
I'm using `logstash@5.5.0` which used `awesome_print` as a dependency, when I run logstash, it raised an error:

```
NameError: undefined local variable or method `dotfile' for #<AwesomePrint::Inspector:0x665967db>
  merge_custom_defaults! at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:163
              initialize at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:50
                      ai at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/awesome_print-1.8.0/lib/awesome_print/core_ext/kernel.rb:9
          encode_default at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-rubydebug-3.0.3/lib/logstash/codecs/rubydebug.rb:39
                    call at org/jruby/RubyMethod.java:120
                  encode at /usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-rubydebug-3.0.3/lib/logstash/codecs/rubydebug.rb:35
            multi_encode at /usr/share/logstash/logstash-core/lib/logstash/codecs/base.rb:50
                    each at org/jruby/RubyArray.java:1613
            multi_encode at /usr/share/logstash/logstash-core/lib/logstash/codecs/base.rb:50
           multi_receive at /usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:90
           multi_receive at /usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/single.rb:15
             synchronize at org/jruby/ext/thread/Mutex.java:149
           multi_receive at /usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/single.rb:14
           multi_receive at /usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:47
            output_batch at /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:420
                    each at org/jruby/RubyHash.java:1342
            output_batch at /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:419
             worker_loop at /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:365
           start_workers at /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:330
```

I have checked my `inspector.rb` Line 163, it is https://github.com/awesome-print/awesome_print/blob/master/lib/awesome_print/inspector.rb#L164

I'm not familiar with ruby, if there is no `.aprc` file or it is not readable, `#{dotfile}` could be undefined ?

**Comment by imajes** [comment]
Yeah, you had another issue, which isn't super clear -- but the real problem is that the rescue error is trying to print a local var it can't reach (as you suspected). We can fix up the error message, but if you change that line to the following, and re-run your app, it should give clearer indication to what's going on:

```$stderr.puts "Issue loading custom defaults. #{e.message}\n#{e.backtrace}"```

**Comment by dawncold** [comment]
Thx, I found the root problem, dotfile path is concatenated by `ENV['HOME']` and `.aprc`, but in my environment, `ENV['HOME']` is `nil`, so the `File.join` raised an exception.

**Comment by iamrohitbanga** [comment]
Sorry Is there a reason this issue is closed? IMHO if ENV['HOME'] is nil the library should assume that .aprc is not present. Is there a plan to update this behavior?

**Comment by iamrohitbanga** [comment]
Is this fixed? There can be situations when ENV['HOME'] is not set. Is it possible to guard against this?

**Comment by imajes** [comment]
Yeah, I just pushed up a commit that resolves this. Thanks!

**Comment by iamrohitbanga** [comment]
awesome_thanks!

**Comment by ranvijayj** [comment]
Error still there in 1.8.0

**Comment by KelseyDH** [comment]
Any progress on this?  Or should projects switch over to `pretty_print`?  I can't use `binding.pry` in rails tests from this issue.

**Comment by KelseyDH** [comment]
Heads up for others encountering this problem with `awesome_print` on Rails:  if you see this error message, it's because your app's `ENV['HOME']` has disappeared.  In my case `awesome_print` failed with this error because we had rspec specs using `stub_const` to stub `ENV` values in tests:

```ruby
# rspec test ...

  before do
    stub_const("ENV", {
        "API_ENABLED" => true
    })
  end
```

which erased all the app's environment variables including `ENV["HOME"]`.  For us rewriting tests like this made the issue go away:

```ruby
  before do
    stub_const 'ENV', ENV.to_h.merge("API_ENABLED" => true)
  end
```
