### ISSUE TITLE
Fix for Issue 316 has not been released, consider publishing 1.8.1 to Rubygems.

### ISSUE THREAD

**Issue by guyboertje** [awesome-print/awesome_print#336]
In the Logstash project, we still get the occasional error where the user has not set ENV['HOME']
It would be really handy to get the fixed error message printed out.

https://github.com/awesome-print/awesome_print/issues/316#issuecomment-328217961

**Comment by KelseyDH** [comment]
Any reason for the delayed release?  This error at a minimum should tell people they need an ENV['HOME'] set if the latest versions aren't ready to be released.
