### ISSUE TITLE
Create a new release, 1.8 contains a BUG

### ISSUE THREAD

**Issue by marcsantiago** [awesome-print/awesome_print#338]
`$stderr.puts "Could not load #{dotfile}: #{e}"`

Causes logstash to fail as dotfile is undefined when calling rescue in `merge_custom_defaults`

**Comment by yaauie** [comment]
@gerrywastaken is there anything I can do to assist in publishing a new release? Users of Logstash are hitting the unset-`HOME` bug that was fixed in [awesome-print/awesome_print@62033856](https://github.com/awesome-print/awesome_print/commit/62033856f8ff08347a9ae20fc0519b2d237e1a15).

**Comment by kares** [comment]
ping here. 
Logstash seems stuck with **1.7.0** since it can not update to **1.8.0** (due this bug).
since Logstash upgraded to Ruby 2.5 its left with a [`Fixnum` warning :crying_cat_face:](https://github.com/logstash-plugins/logstash-codec-rubydebug/issues/7)

**Comment by BryanH** [comment]
A new version is in the works. I'm wading through the long backlog of PRs that are desperately needed and will push out a new version soon. Please let me know if the issue still occurs (and a PR is always appreciated!)
