### ISSUE TITLE
AwesomePrint.pry! overrides Pry's auto-pagination

### ISSUE THREAD

**Issue by booch** [awesome-print/awesome_print#347]
Using `output.puts` overrides Pry's auto-pagination, forcing the output to be printed directly.

**Comment by quetzalcoatl** [comment]
FYI: https://github.com/pry/pry/wiki/FAQ#awesome_print

    Pry.config.print = proc { |output, value| Pry::Helpers::BaseHelpers.stagger_output("=> #{value.ai}", output) }

**Comment by BryanH** [comment]
If you want to make a pull request to implement this - please do and reopen!
