### ISSUE TITLE
possible to hide some record attributes in ai ?

### ISSUE THREAD

**Issue by MathieuDerelle** [awesome-print/awesome_print#368]
example : a model Country with an attribute `:geometry` containing the geometry to display on a map (i.e all the coordinates on the border)

There are long long long arrays which are unreadable in the console
(console which uses `ai` output : 
`Pry.config.print = proc { |output, value| output.puts value.ai }`)

Is is possible to mark this attribute `:geometry` in some way,
in order to not show it in `ai` output ?

**Comment by BryanH** [comment]
PRs are always welcome. Is this the behavior you are looking for?

### Data example
`a = { 'foo':'bar', 'alpha':'beta' }`

Mark key `alpha` as not displayed (config? or on each call?)

### Desired output
    a = {
      'foo': 'bar'
    }

...or something like that
