### ISSUE TITLE
Proc.new is deprecated

### ISSUE THREAD

**Issue by navid-farjad** [awesome-print/awesome_print#387]
iam facing very annoying warning: 
/.rvm/gems/ruby-2.7.0/gems/awesome_print-1.8.0/lib/awesome_print/formatters/base_formatter.rb:113: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead

It's all over the console for every call. please let me know how can I fix it. 
Rails 6.0.3.2
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]

Thank you

**Comment by hasannadeem** [comment]
I'm having the same issue. 😞

**Comment by chaoxng** [comment]
Try https://github.com/amazing-print/amazing_print

**Comment by BryanH** [comment]
Thanks for the PRs - I am working on merging

**Comment by BryanH** [comment]
Fixed with latest PR. I'll cut a new version after more cleanup

**Comment by ashleyconnor** [comment]
Any ETA on `1.9.0` being published on rubygems?
