### ISSUE TITLE
problem with rails and ruby 3.0.0

### ISSUE THREAD

**Issue by igortice** [awesome-print/awesome_print#410]
![Captura de Tela 2021-03-03 às 21 20 26](https://user-images.githubusercontent.com/1306646/109890591-4caf5700-7c66-11eb-8077-bbc69444c875.png)

**Comment by Maarius** [comment]
I have the same issue, here my environment:
```
OS: macOS Big Sur
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
Rails 6.1.2.1
awesome_print-1.8.0
```
Just tried, same issue with `awesome_print 2.0.0.pre2`

**Comment by Maarius** [comment]
@igortice latest `master` branch from Github is working in my environment. 
Just use this line in your `Gemfile`:
```
gem 'awesome_print', git: 'https://github.com/awesome-print/awesome_print'
```

**Comment by igortice** [comment]
> @igortice latest `master` branch from Github is working in my environment.
> Just use this line in your `Gemfile`:
> 
> ```
> gem 'awesome_print', git: 'https://github.com/awesome-print/awesome_print'
> ```
