### ISSUE TITLE
Getting FrozenError (can't modify frozen String: "false") after upgrading to Ruby 2.7.3 using awesome_print (1.9.2)

### ISSUE THREAD

**Issue by ritec** [awesome-print/awesome_print#414]
Recently upgraded to Ruby 2.7.3 and all of the sudden we are getting the error below

```
irb(main):005:0> ap User.last
Traceback (most recent call last):
FrozenError (can't modify frozen String: "false")
```
 I upgraded awesome print to the latest `awesome_print (1.9.2)` but we are still having the same issue. 
This error happens when `ap` is used before any ActiveRecord call. Any ideas?

Weird, it looks like it works on some models and not on others. Simpler models seem to work, more complex models have the freeze issue.

**Comment by ryansch** [comment]
@ritec This is unrelated to `awesome_print`. Upgrade `irb` and `reline` and you should see the issue disappear.

**Comment by ritec** [comment]
@ryansch Oh wow, I did not have much time to research in depth but I will close the issue now then. Thanks for the heads up!

**Comment by ritec** [comment]
@ryansch hmmm upgraded both and still having the same issue.

**Comment by ryansch** [comment]
@ritec If you're using bundler, you need to specify them in your `Gemfile`.

**Comment by ritec** [comment]
ok thanks, I now did that and nothing prints when  I do `ap User.last` for example, but I don't want this to turn into a help me session more than it has so I will go ahead and leave it at that. Thanks. Something funky is definitely going on here.
