### ISSUE TITLE
Don't override/monkey patch `String` class

### ISSUE THREAD

**Issue by n-rodriguez** [awesome-print/awesome_print#419]
This is pretty unexpected : https://github.com/awesome-print/awesome_print/blob/master/lib/awesome_print/core_ext/string.rb

Defining those methods here https://github.com/awesome-print/awesome_print/blob/master/lib/awesome_print/colorize.rb with a `string` argument would be cleaner.

**Comment by zw963** [comment]
Yes, i notice, ap auto require `awesome_print/core_ext/string.rb`

if make String#instance_methods more confusing ...

**Comment by zw963** [comment]
Maybe we should add a config option to permit disable it.

**Comment by n-rodriguez** [comment]
> Maybe we should add a config option to permit disable it.

or implement it properly : https://github.com/awesome-print/awesome_print/pull/421
